export const OpCode = Object.freeze({
  NOP: { IMPLIED: 0xea } as const,
  LDA: { ABSOLUTE: 0xad, IMMEDIATE: 0xa9 } as const,
  JMP: { ABSOLUTE: 0x4c } as const,
  JSR: { ABSOLUTE: 0x20 } as const,
  STA: { ABSOLUTE: 0x8d } as const,
  ROR: { ACCUMULATOR_A: 0x6a } as const,
  ROL: { ACCUMULATOR_A: 0x2a } as const,
  TXA: { IMPLIED: 0x8a } as const,
  TAY: { IMPLIED: 0xa8 } as const,
  TAX: { IMPLIED: 0xaa } as const,
  TYA: { IMPLIED: 0x98 } as const,
  RTS: { IMPLIED: 0x60 } as const,
  PLA: { IMPLIED: 0x68 } as const,
  PHA: { IMPLIED: 0x48 } as const,
  DEX: { IMPLIED: 0xca } as const,
  BNE: { RELATIVE: 0xd0 } as const,
  CLC: { IMPLIED: 0x18 } as const,
  ADC: { ABSOLUTE: 0x6d } as const,
} as const);
